# CQ-15: What type of actions were performed during audit trail events (e.g., created, modified)?
# needs population confirmation.

PREFIX aml: <http://www.w3.org/animl/ontology/>

SELECT ?actionType
WHERE {
    ?auditEntry a aml:AuditTrailEntry .
    ?auditEntry aml:makesChange .
    ?change a aml:Change ;
    ?change aml:hasType ?actionType .
            

}