# CQ-16: Which samples were consumed in an experiment step?
# needs population confirmation.

PREFIX aml: <http://www.w3.org/animl/ontology/>

SELECT ?Sample
WHERE {
    ?step a aml:ExperimentStep ;
          aml:includesInfrastructure ?infrastructure .
          
    ?infrastructure aml:includes ?referenceSet .
    ?infrastructure aml:hasPart ?itemSpec  .
    
    ?referenceSet aml:hasMember ?reference .
    
    ?reference aml:pointsTo ?Sample .
    
    ?Sample a aml:Sample .

    ?step aml:usesTechnique ?Technique .

    ?Technique aml:includes ?itemSpec .

    ?Technique aml:consumes ?ReferenceSpec .

    ?reference aml:hasSpecification ?ReferenceSpec



}