# CQ-17: What is the label of a unit?
# needs population confirmation.

PREFIX aml: <http://www.w3.org/animl/ontology/>

SELECT ?label
WHERE {
    ?unit a aml:Units ; # or aml:SIUnit
          aml:label ?label .
}