# CQ-19: What are the required data types for series in a technique definition?
# needs population confirmation.
SELECT ?dataType
WHERE {
    ?technique aml:includes ?specification .
    
    ?specification a aml:SeriesSpecification ;
                   aml:hasType ?dataType .
                   
    # ?dataType matches instances like aml:float32, aml:int32, etc.
}