# CQ-20: What is the version of a software agent?
# needs population confirmation.
PREFIX aml: <http://www.w3.org/animl/ontology/>

SELECT ?softwareVersion
WHERE {
    ?software a aml:Agent .
    ?software aml:hasType ?Type .
    FILTER (?Type = aml:SoftwareAgent) .
    ?software aml:version ?softwareVersion .

}