# CQ-21: When was a specific change made?
# needs population confirmation.
PREFIX aml: <http://www.w3.org/animl/ontology/>

SELECT ?timestamp
WHERE {
    ?change a aml:Change .
    ?AuditTrailEntry a aml:AuditTrailEntry .
    ?AuditTrailEntry aml:makesChange ?change .
    ?AuditTrailEntry aml:timestamp ?timestamp .
}
