# CQ-23: What series are defined in a series set blueprint for a technique?
# needs population confirmation.
PREFIX aml: <http://www.w3.org/animl/ontology/>

SELECT ?series
WHERE {
    ?seriesSet a aml:SeriesSet .
    ?seriesSet aml:hasSpecification ?SeriesSetSpecification .
    ?SeriesSetSpecification aml:usesTechnique ?Technique .
    ?Technique a aml:Technique .
    ?Technique aml:includes ?seriesSpecification .
    ?seriesSpecification a aml:seriesSpecification .
    ?series aml:hasSpecification ?seriesSpecification .
}