# CQ-27: What role did a specific sample used in an experimentStep play?
# needs population confirmation.

PREFIX aml: <http://www.w3.org/animl/ontology/>

SELECT ?role ?ExperimentStep ?Sample
WHERE {
    # Match the reference linking a specific sample
    ?Step a aml:ExperimentStep .
    {
        ?Step aml:producesResult ?Result .
        ?Infrastructure aml:includes ?ReferenceSet .
        ?ReferenceSet aml:hasMember ?reference .
    }
    UNION
    {
        ?Step aml:includesInfrastructure ?Infrastructure .
        ?Result aml:includes ?ReferenceSet .
        ?ReferenceSet aml:hasMember ?reference .
    }
    ?reference a aml:AnimlReference .
    ?Sample a aml:Sample .

    ?ReferenceSet aml:hasSpecification ?AnimlReferenceSpecification .
    ?AnimlReferenceSpecification a aml:AnimlReferenceSpecification .
    ?Technique ?role ?AnimlReferenceSpecification .
}