# CQ-29: What are the roles of an agent outside of the experiment?
# # needs population confirmation.

PREFIX aml: <http://www.w3.org/animl/ontology/>
PREFIX bag: <http://www.ontologydesignpatterns.org/cp/owl/bag.owl#>

SELECT ?Type ?Role ?organisation
WHERE {
    ?author a aml:Agent .
    ?author bag:isClassifiedBy ?Role .
    ?author aml:hasType ?Type .
    ?author aml:organisation ?organisation .
    FILTER NOT EXISTS { 
        ?Role aml:requiresRole ?AuditTrailEntry . 
        ?AuditTrailEntry a aml:AuditTrailEntry .
    }
}