# CQ-32: Who is the manufacturer of a device?
# needs population confirmation.

PREFIX aml: <http://www.w3.org/animl/ontology/>

SELECT ?device ?manufacturer
WHERE {
    ?device a aml:Agent ;
            aml:organisation ?manufacturer .
    ?Agent aml:hasType ?Type .
    FILTER(?Type = aml:HardwareAgent)
}
