# CQ-33: What is the container type for a sample?
# needs population confirmation.
PREFIX aml: <http://www.w3.org/animl/ontology/>

SELECT ?Sample ?containerType
WHERE {
    ?sample a aml:Sample ;
            aml:isContained ?situation .

    ?situation a aml:SampleInContainer ;
               aml:isContainedBy ?container .

    ?container a aml:Container ;
               aml:hasContainerType ?containerType .
               
    ?containerType a aml:ContainerType .
}