# CQ-36: What is the expected dependency (independent/dependent) for a series in a technique?
# The Technique Module shows aml:SeriesSpecification with the data property aml:dependency.

PREFIX aml: <http://www.w3.org/animl/ontology/>

SELECT ?dependency
WHERE {
    ?seriesSpec a aml:SeriesSpecification ;
                aml:dependency ?dependency .
                
}