# CQ-38: What are the individual string values in a series?
# needs population confirmation.

PREFIX aml: <http://www.w3.org/animl/ontology/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT ?series ?stringValue
WHERE {
    ?series a aml:Series ;
            aml:value ?stringValue .
    ?series aml:hasSpecification ?seriesSpec .
    ?seriesSpec aml:hasType ?dataType .
    FILTER(?dataType = aml:string)
            
    FILTER (datatype(?stringValue) = xsd:string)
}
ORDER BY ?series ?stringValue