# CQ-40: What is the end value of a parent data point reference?
# The Reference Pattern explicitly defines aml:startValue and aml:endValue on the aml:AnimlReference class to support data slicing.

PREFIX aml: <http://www.w3.org/animl/ontology/>
PREFIX set: <http://www.ontologydesignpatterns.org/cp/owl/sequence.owl#>

SELECT ?referenceSet ?Series ?DataPoint
WHERE {
    ?referenceSet a aml:AnimlReferenceSet .
    ?referenceSet aml:subject ?Series .
    ?referenceSet aml:hasMember ?reference .
    ?reference aml:pointsTo ?DataPoint .
    FILTER NOT EXISTS {
        ?DataPoint aml:directlyPrecedes ?x .
    }
}
ORDER BY ?referenceSet ?Series ?DataPoint