# CQ-6: What is the unique identifier of the device?
# requries populated validation

PREFIX aml: <http://www.w3.org/animl/ontology/>

SELECT ?deviceID
WHERE {
    ?device a aml:HardwareAgent ;
            aml:identifier ?deviceID .
    
}
