# CQ-7: What is the stated purpose of a sample being used?
# requries populated validation
PREFIX aml: <http://www.w3.org/animl/ontology/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?function
WHERE {
    ?Technique a aml:Technique .
    
    ?referenceSpecification a aml:AnimlReferenceSpecification .

    {
        ?technique a aml:Technique ;
                   aml:derives ?referenceSpecification .
    }
    UNION
    {
        ?technique a aml:Technique ;
                   aml:consumes ?referenceSpecification .
    }

    ?reference aml:hasSpecification ?referenceSpecification .

    ?referenceSpecification aml:hasFunction ?Function .
}