# CQ-8: What are the individual 32-bit integer values in a series?
# requries populated validation
PREFIX aml: <http://www.w3.org/animl/ontology/>

SELECT ?dataPoint
WHERE {
    ?series a aml:Series .
    ?series aml:hasSpecification ?seriesSpecification .
    ?seriesSpecification aml:hasType ?dataType .
    FILTER (?dataType = aml:int32) .
    ?series aml:hasMember ?dataPoint

}