# CQ-100: What are the names of the result definitions specified by a technique?

PREFIX aml: <http://www.w3id.org/animl/ontology/>

SELECT ?resultDefName
WHERE {
    ?technique a aml:technique .
    ?xpstep a aml:experimentStep ;
                aml:usesTechnique ?technique ;
                aml:producesResult ?resultSpec .
               
    ?resultSpec a aml:resultSpecification ;
                aml:name ?resultDefName .
}