PREFIX aml: <http://www.w3id.org/animl/ontology/>
# CQ-19: What are the required data types for series in a technique definition?
SELECT ?technique ?series ?dataType
WHERE {
    ?technique aml:includes ?specification .
  	?specification a aml:SeriesSpecification .
  	?specification aml:hasType ?dataType .
  	?series aml:hasSpecification ?specification
}