# CQ-2: What is the phone number of an author?
# requires populated testing
PREFIX aml: <http://www.w3id.org/animl/ontology/>

SELECT ?Agent ?phoneNumber
WHERE {
    ?Agent a aml:Agent ;
           aml:phone ?phoneNumber .
    ?Agent aml:isClassifiedBy ?Role.
    ?Role aml:hasType ?RoleType .
    FILTER (?RoleType = aml:Author)
}