# CQ-20: What is the version of a software agent?
PREFIX aml: <http://www.w3id.org/animl/ontology/>

SELECT ?software ?softwareVersion
WHERE {
    ?software a aml:agent .
    ?software aml:hasType ?Type .
    FILTER (?Type = aml:SoftwareAgent) .
    ?software aml:version ?softwareVersion .

}