# CQ-21: When was a specific change made?
PREFIX aml: <http://www.w3id.org/animl/ontology/>

SELECT ?AuditTrailEntry ?change ?timestamp
WHERE {
    ?change a aml:change .
    ?AuditTrailEntry a aml:auditTrailEntry .
    ?AuditTrailEntry aml:makesChange ?change .
    ?AuditTrailEntry aml:timeStep ?timestamp .
}
ORDER BY ?timestamp
