# CQ-22: What is the maximum number of samples allowed for a given role in a technique definition?

PREFIX aml: <http://www.w3id.org/animl/ontology/>

SELECT ?maxSamples
WHERE {
    ?technique aml:hasPart ?role .
    
    ?role a aml:Role ;
          aml:maxCardinality ?maxSamples .
}