# CQ-23: What series are defined in a series set blueprint for a technique?
PREFIX aml: <http://www.w3id.org/animl/ontology/>

SELECT ?outer_technique ?seriesSet ?series
WHERE {
    ?seriesSet a aml:seriesSet .
    ?seriesSet aml:hasSpecification ?SeriesSetSpecification .
    ?outer_technique aml:includes ?SeriesSetSpecification .
  	?SeriesSetSpecification aml:usesTechnique ?technique .
  	?technique aml:includes ?seriesSpecification .
  	?series aml:hasSpecification ?seriesSpecification .
}