# CQ-24: What role did the data from a previous experiment step play?

PREFIX aml: <http://www.w3id.org/animl/ontology/>

SELECT ?role
WHERE {
    # The reference exists within the current step's context
    ?reference a aml:AnimlReference ;
               aml:pointsTo ?previousStep ;
               aml:hasFunction ?role .
               
    ?previousStep a aml:ExperimentStep .
}