# CQ-26: What changes have been recorded in the audit trail?
PREFIX aml: <http://www.w3id.org/animl/ontology/>

SELECT ?auditTrail ?entry ?change
WHERE {
    ?auditTrail a aml:auditTrail ;
                aml:hasAuditTrailEntry ?entry .
                
    ?entry a aml:auditTrailEntry ;
           aml:makesChange ?change .
}