# CQ-29: What is the role of an author within their organization?

PREFIX aml: <http://www.w3id.org/animl/ontology/>

SELECT ?organizationRole
WHERE {
    ?author a aml:agent ;
            aml:hasRole ?organizationRole .
}