# CQ-30: What is the physical location of an agent?
# needs population confirmation.

PREFIX aml: <http://www.w3id.org/animl/ontology/>

SELECT ?author ?location
WHERE {
    ?author a aml:Agent ;
            aml:location ?location .
}