# CQ-40: What is the end value of a parent data point reference?

PREFIX aml: <http://www.w3.org/animl/ontology/>

SELECT ?endValue
WHERE {
    ?reference a aml:AnimlReference ;
               aml:endValue ?endValue .
}