# CQ-41: What is the maximum number of times a specific result can occur according to its blueprint?

PREFIX aml: <http://www.w3id.org/animl/ontology/>

SELECT ?maxOccurs
WHERE {
    # Assuming ResultSpecification is a subclass of Specification
    ?resultSpec a aml:resultSpecification ; 
                aml:maxCardinality ?maxOccurs .
}