# CQ-47: When was an experiment step performed?
PREFIX aml: <http://www.w3id.org/animl/ontology/>

SELECT ?step ?parameter ?startTime
WHERE {
    ?step a aml:ExperimentStep .
  	?step aml:producesResult ?result .
    ?result aml:hasResultCategory ?category .
    ?category aml:hasParameter ?parameter .
    ?parameter aml:name "Start Time" ;
               aml:value ?startTime .
}