# CQ-51: Was a sample in an experiment step inherited from a parent step?

PREFIX aml: <http://www.w3id.org/animl/ontology/>

ASK {
    # Current step uses a sample
    ?currentStep a aml:experimentStep ;
                 aml:hasInfrastructure ?infra .
    ?infra aml:includes/aml:hasMember/aml:pointsTo ?sample .

    # A different step produced/defined that sample
    ?parentStep a aml:experimentStep ;
                aml:hasResult ?result .
    ?result aml:includes/aml:hasMember/aml:pointsTo ?sample .

    FILTER (?currentStep != ?parentStep)
}