# CQ-58: What is the new value of an item that was changed?

PREFIX aml: <http://www.w3id.org/animl/ontology/>

SELECT ?newValue
WHERE {
    ?change a aml:Change ;
            aml:newValue ?newValue .
}