# CQ-6: What is the unique identifier of the device?

PREFIX aml: <http://www.w3id.org/animl/ontology/>

SELECT ?device ?deviceID
WHERE {
    ?device a aml:agent ;
            aml:hasType aml:hardwareAgent ;
            aml:identifier ?deviceID .
}
