# CQ-62: What units are allowed for a specific quantity in a technique definition?

PREFIX aml: <http://www.w3id.org/animl/ontology/>

SELECT ?unit
WHERE {
    ?unit a aml:units ;
          aml:quantity "QuantityNamePlaceholder" .
}