# CQ-63: What is the firmware version of the device?

PREFIX aml: <http://www.w3.org/animl/ontology/>

SELECT ?firmwareVersion
WHERE {
    ?device a aml:HardwareAgent ;
            aml:firmwareVersion ?firmwareVersion .
}