# CQ-64: What is the URI of the technique definition used in an experiment step?
PREFIX aml: <http://www.w3id.org/animl/ontology/>

SELECT ?techniqueURI
WHERE {
    ?step a aml:experimentStep ;
          aml:hasTechnique ?techniqueURI .
}