# CQ-69: What literature references are cited in a technique definition?

PREFIX aml: <http://www.w3id.org/animl/ontology/>

SELECT ?citation
WHERE {
    ?technique a aml:Technique ;
               aml:citation ?citation .
}