# CQ-70: What is the name of the method used in an experiment step?
PREFIX aml: <http://www.w3id.org/animl/ontology/>

SELECT ?methodName
WHERE {
    ?step a aml:experimentStep ;
          aml:hasMethod ?method .
          
    ?method aml:name ?methodName .
}