# CQ-75: What technique extensions were applied in an experiment step?
PREFIX aml: <http://www.w3id.org/animl/ontology/>

SELECT ?baseTechnique
WHERE {
    ?step a aml:experimentStep ;
          aml:usesTechnique ?appliedTechnique .
          
    ?appliedTechnique aml:extends ?baseTechnique .
}