# CQ-76: How is a unit defined using SI base units?

PREFIX aml: <http://www.w3id.org/animl/ontology/>

SELECT ?factor ?exponent ?offset
WHERE {
    ?unit a aml:sIUnit ;
          aml:factor ?factor ;
          aml:exponent ?exponent ;
          aml:offset ?offset .
}