# CQ-79: Is a series intended to be visible by default in a plot?

PREFIX aml: <http://www.w3.org/animl/ontology/>

SELECT ?isVisible
WHERE {
    ?seriesSpec a aml:SeriesSpecification ;
                aml:isVisible ?isVisible .
}