# CQ-87: What is the start value for an auto-incremented series?


PREFIX aml: <http://www.w3id.org/animl/ontology/>

SELECT ?startValue
WHERE {
    ?autoIncrementedEncoding a aml:AutoIncrementedEncodingType ;
                             aml:startValue ?startValue .
}