# CQ-9: What is the sample ID of those containers in which a sample is located?
PREFIX aml: <http://www.w3id.org/animl/ontology/>

SELECT ?Container ?Sample ?containerID ?Situation
WHERE {
    ?Container a aml:container .
    ?Container aml:containerID ?containerID .
  
    ?Sample a aml:sample .
  
    ?Situation a aml:sampleInContainer .
    ?Situation aml:isContainedBy ?Container .
  	?Sample aml:isContained ?Situation .
    FILTER ( ?Container != ?Sample )
}