# CQ-90: What are the allowed enumerated values for a string parameter in a technique definition?

PREFIX aml: <http://www.w3id.org/animl/ontology/>

SELECT ?allowedValue
WHERE {
    ?paramSpec a aml:parameterSpecification ;
               aml:hasAllowedValue ?allowedValue .
}