# CQ-98: Which template was used for a specific experiment step?

PREFIX aml: <http://www.w3id.org/animl/ontology/>

SELECT ?template
WHERE {
    ?step a aml:experimentStep ;
          aml:isItemOf ?template .
    
    ?template a aml:template .
}